### ISSUE TITLE
Error while trying to retrieve access token

### ISSUE THREAD

**Issue by hrushikesht** [saurabhbatra96/drive-sync#23]
After copying the token from google website, I got this error.
`Error while trying to retrieve access token { [Error: tunneling socket could not be established, cause=write EPROTO] code: 'ECONNRESET' }`

**Comment by saurabhbatra96** [comment]
Make sure your https_proxy environment variable is set (`printenv | grep https_proxy`).

**Comment by dalmia** [comment]
Verified. Actually setting HTTPS_PROXY worked.

**Comment by dalmia** [comment]
On using:
```
drive-sync down all
```
I get this error after the first file got downloaded:
```
tumor_089.tif downloaded.
buffer.js:23
  const ui8 = new Uint8Array(size);

RangeError: Invalid typed array length
    at new Uint8Array (native)
    at createBuffer (buffer.js:23:15)
    at allocate (buffer.js:98:12)
    at new Buffer (buffer.js:53:12)
    at Function.Buffer.concat (buffer.js:236:16)
    at BufferList.copy (/home/path/to/drive-sync/node_modules/bl/bl.js:124:21)
    at BufferList.slice (/home/path/to/drive-sync/node_modules/bl/bl.js:99:15)
    at BufferList.toString (/home/path/to/drive-sync/node_modules/bl/bl.js:166:15)
    at Request.<anonymous> (/home/path/to/drive-sync/node_modules/request/request.js:1035:36)
    at emitOne (events.js:82:20)

```
Could you please help me here?

**Comment by dalmia** [comment]
Also, when I download an individual file, I get this error:
```
Tumor_016.tif downloaded.
buffer.js:385
    throw new Error('toString failed');
    ^

Error: toString failed
    at Buffer.toString (buffer.js:385:11)
    at BufferList.toString (/home/path/to/drive-sync/node_modules/bl/bl.js:166:33)
    at Request.<anonymous> (/home/path/to/drive-sync/node_modules/request/request.js:1035:36)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/home/path/to/drive-sync/node_modules/request/request.js:1003:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at nextTickCallbackWith2Args (node.js:441:9)
```
Actually, my file is quite big (`dtype` is `uint16`) and that might be the reason for the error. Any solution?
